### ISSUE TITLE
Do not block menu-items that contain submenus

### ISSUE THREAD

**Issue by TimvanSteenbergen** [bsgriggs/mendix-unsaved-changes-message#3]
Great tool. Just one improvement that would make it even better:
When clicking on a menu-item, you would expect that click to just open up the menu, showint the sub-items, and without popping you the block question.

Best regards and have a nice day!

**Comment by bsgriggs** [comment]
Duplicate of https://github.com/bsgriggs/mendix-unsaved-changes-message/issues/2
